name: 📊 Gist Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SolitaryJune
          config_output: gist
          gist: SolitaryJune/你的GistID
          filename: github-metrics.svg

          base: header, activity, community
          plugin_languages: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_traffic: yes
          config_timezone: Asia/Shanghai
          gist_token: ${{ secrets.GIST_TOKEN }}
